name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r Scripts/requirements.txt
          pip install gdown joblib streamlit fastapi uvicorn

      - name: Download data
        run: |
          mkdir -p data
          gdown https://drive.google.com/uc?id=1OwcdGd6XnArAYAcsp56j5mYG0VNa61rL -O data/df_train_cleaned.csv
          gdown https://drive.google.com/uc?id=1UMvwZ1eDtS1Ad-VU9bZJZokqU0O3r5AK -O data/df_test_cleaned.csv

      - name: Train model and save report
        run: python Scripts/train_model.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            models/model.joblib
            results/report.txt

  test:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r Scripts/requirements.txt
          pip install gdown joblib streamlit fastapi uvicorn

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: ./artifacts

      - name: Start FastAPI server
        run: |
          nohup uvicorn Scripts.fast_api:app --host 127.0.0.1 --port 8000 > fastapi.log 2>&1 &
          for i in {1..10}; do
            echo "⏳ Waiting for FastAPI to be ready... attempt $i"
            curl -s http://127.0.0.1:8000/docs > /dev/null && echo "✅ FastAPI is up!" && break
            sleep 2
          done

      - name: Run tests
        run: python Scripts/test_predict.py

  
 # deploy:
   # runs-on: ubuntu-latest
   # needs: test

   # steps:
   # - uses: actions/checkout@v3

   # - name: Set up Pyt     # uses: actions/setup-python@v4
     # with:
       # python-version: '3.9'

   # - name: Install dependencies
     # run: |
       # python -m pip install --upgrade pip setuptools wheel
       # pip install streamlit joblib

   # - name: Download artifacts
     # uses: actions/download-artifact@v3
     # with:
       # name: model-artifacts
       # path: ./artifacts

   # - name: Run Streamlit app (example: Start Server)
     # run: streamlit run Scripts/AppStreamlit.py
