name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r Scripts/requirements.txt
        pip install pytest requests

    - name: Lancer les tests
      run: |
        pytest tests/

    - name: Entraîner le modèle
      run: |
        python Scripts/train_model.py

    - name: Démarrer FastAPI en arrière-plan
      run: |
        uvicorn fast_api:app --host 127.0.0.1 --port 8000 &
        sleep 10
        curl --retry 5 --retry-delay 2 --retry-connrefused http://127.0.0.1:8000/

    - name: Tester l'API FastAPI
      run: |
        python tests/test_predict.py

    - name: Sauvegarder le modèle en tant qu'artifact
      uses: actions/upload-artifact@v3
      with:
        name: modele-entrainé
        path: models/
