jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r Scripts/requirements.txt
        pip install pytest requests uvicorn

    - name: Entraîner le modèle
      run: python Scripts/train_model.py

    - name: Démarrer FastAPI en arrière-plan
      run: |
        uvicorn Scripts.fast_api:app --host 127.0.0.1 --port 8000 &
        sleep 10

    - name: Tester l'API FastAPI
      run: python tests/test_predict.py

    - name: Lancer les autres tests
      run: pytest tests/

