name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name:  Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name:  Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancer les tests
      run: |
        pytest tests/

    - name: Entraîner le modèle
      run: |
        python train_model.py
    - name: Demarrage FastAPI en arrière-plan
      run: |
        uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 5  # attendre que l'API démarre
    - name: Tester l'API FastAPI
      run: |
        python test_predict.py
    - name: Sauvegarder le modèle en tant qu'artifact
      uses: actions/upload-artifact@v3
      with:
        name: modele-entrainé
        path: models/
