name: Test FastAPI + Model

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r Scripts/requirements.txt

      - name: Generate model
        run: |
          python Scripts/train_model.py
        # Ce script doit créer `artifacts/model.joblib`

      - name: Run FastAPI
        run: |
          nohup uvicorn Scripts.fast_api:app --host 127.0.0.1 --port 8000 > fastapi.log 2>&1 &

      - name: Wait for API to start
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:8000 && break
            echo "Waiting for FastAPI to start..."
            sleep 2
          done

      - name: Run API tests
        run: python test_predict.py
 
 # deploy:
   # runs-on: ubuntu-latest
   # needs: test

   # steps:
   # - uses: actions/checkout@v3

   # - name: Set up Pyt     # uses: actions/setup-python@v4
     # with:
       # python-version: '3.9'

   # - name: Install dependencies
     # run: |
       # python -m pip install --upgrade pip setuptools wheel
       # pip install streamlit joblib

   # - name: Download artifacts
     # uses: actions/download-artifact@v3
     # with:
       # name: model-artifacts
       # path: ./artifacts

   # - name: Run Streamlit app (example: Start Server)
     # run: streamlit run Scripts/AppStreamlit.py
